project:
  type: website

website:
  title: "raianerosseti"
  navbar:
    left:
      - href: about.qmd
        text: Quem sou eu?
      - Projetos.qmd
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    lang: pt

editor: visual